version: '3'
services:
  app:
    image: 'gcr.io/${PROJECT_ID}/${IMAGE_NAME}'
    tty: true
    volumes:
      - .:/workspace:cached
    working_dir: /workspace
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
